In [5]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.model_selection import KFold

In [6]:
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size= 0.3)

In [14]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

c:\Users\spoorthi.sheregar\AppData\Local\Continuum\anaconda3\envs\sp_env_ml\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [15]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9777777777777777

In [16]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9685185185185186

In [8]:
kf = KFold(n_splits= 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print (train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [12]:
from sklearn.model_selection import StratifiedKFold

In [13]:
folds = StratifiedKFold(n_splits= 3)

In [25]:
scores_l = []
scores_svm = []
scores_rf = []
for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index] , digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators= 40),X_train, X_test, y_train, y_test))

c:\Users\spoorthi.sheregar\AppData\Local\Continuum\anaconda3\envs\sp_env_ml\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\spoorthi.sheregar\AppData\Local\Continuum\anaconda3\envs\sp_env_ml\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solve

In [26]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [27]:
scores_rf

[0.9332220367278798, 0.9415692821368948, 0.9098497495826378]

In [28]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]